#pragma once

enum ofxMouseCursorType {
    CURRENT_SYSTEM_CURSOR,
    ARROW_CURSOR,
    I_BEAM_CURSOR,
    POINTING_HAND_CURSOR,
    CLOSED_HAND_CURSOR,
    OPEN_HAND_CURSOR,
    RESIZE_LEFT_CURSOR,
    RESIZE_RIGHT_CURSOR,
    RESIZE_LEFT_RIGHT_CURSOR,
    RESIZE_UP_CURSOR,
    RESIZE_DOWN_CURSOR,
    RESIZE_UP_DOWN_CURSOR,
    CROSSHAIR_CURSOR,
    DISAPPEARING_ITEM_CURSOR,
    OPERATION_NOT_ALLOWED_CURSOR,
    DRAG_LINK_CURSOR,
    DRAG_COPY_CURSOR,
    CONTEXTUAL_MENU_CURSOR,
    I_BEAM_CURSOR_FOR_VERTICAL_LAYOUT,
};